### ISSUE TITLE
Doesn't run on Firefox / Greasemonkey

### ISSUE THREAD

**Issue by Philville2** [dithpri/RCES#2]
For I followed your notes for creating containers in Firefox but I couldn't get any of these dilema scripts to run.  Further investigation seems that '@run-at document-body' isn't a valid parameter for firefox see: [https://github.com/greasemonkey/greasemonkey/issues/3010](https://github.com/greasemonkey/greasemonkey/issues/3010) and [https://wiki.greasespot.net/Metadata_Block#.40run-at](https://wiki.greasespot.net/Metadata_Block#.40run-at)

So I changed them all to '@run-at  document-end' and NsIssueOpener and NsIssueCompactorRand seem to be working fine. However NsDilemmaAutoClose doesn't appear to do anything and the tab never closes.

**Comment by dithpri** [comment]
Thanks for the report.
Changing all of them to `@run-at document-end` does work indeed.
I'll have to dig in to the NsDilemmaAutoClose issue. Because GM doesn't yet offer support for `@grant window.close` (greasemonkey/greasemonkey#2538), a hackier way of forcing the window to close is needed

**Comment by dithpri** [comment]
Please use [this script](https://github.com/dithpri/RCES/blob/GM-Hacks/userscripts/issue_answering/NsIssueCompactorRand.user.js) for the GreaseMonkey version of `NsIssueCompactorRand`, which allows the autoclose to work as intended. After some thought, I'm not merging it to master because it's a bit hacky and causes the tabs to flicker (opens a new tab and immediately closes the current one) – it's not an improvement for existing non-GM users. A GM install link has been added in the readme.
